nav:
  - Getting started:
      - Quickstart: index.md
      - getting-started/introduction.md
      - Concepts:
          - IO: getting-started/concepts/io.md
          - Nodes: getting-started/concepts/nodes.md
          - Catalogs: getting-started/concepts/catalogs.md
          - Hooks: getting-started/concepts/hooks.md
  - Guides & examples:
      - guides/run_and_viz.md
      - guides/node_parameters.md
      - IO:
        - Custom IO: guides/custom_io.md
        - Parametrizing IO: guides/parametrized_io.md
        - Lazy IO: guides/lazy_io.md
        - Cloud storage: guides/cloud_storage.md
      - guides/testing_nodes.md
      - Examples:
          - Benchmark runtimes: guides/examples/benchmark_node_runtime.md
      # TODO: Add an example project
  - Packages: packages.md
  - API: api
  - Contributing:
      - How to: CONTRIBUTING.md
      - Acknowledgements: contributing/acknowledgements.md
      - Documentation setup: contributing/documentation.md
